<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE utcs_project [
   <!ELEMENT utcs_project ANY>
   <!ATTLIST utcs_project version_major CDATA #REQUIRED
                  version_minor CDATA #REQUIRED
                  id1 CDATA #REQUIRED
                  id2 CDATA #REQUIRED
                  icon CDATA "_0x0"
                  last_unique_id CDATA #REQUIRED>
   <!ELEMENT modified ANY>
   <!ATTLIST modified year CDATA #REQUIRED
                  month CDATA #REQUIRED
                  day CDATA #REQUIRED
                  hour CDATA #REQUIRED
                  minute CDATA #REQUIRED>
   <!ELEMENT customer_info ANY>
   <!ATTLIST customer_info name CDATA ""
                  address CDATA ""
                  city CDATA ""
                  zipcode CDATA ""
                  country CDATA ""
                  phone CDATA ""
                  mobilephone CDATA ""
                  email CDATA ""
                  udf CDATA "">
   <!ELEMENT installer_info ANY>
   <!ATTLIST installer_info name CDATA ""
                  address CDATA ""
                  city CDATA ""
                  zipcode CDATA ""
                  country CDATA ""
                  phone CDATA ""
                  mobilephone CDATA ""
                  email CDATA ""
                  udf CDATA "">
   <!ELEMENT project_info ANY>
   <!ATTLIST project_info programmer CDATA ""
                  number CDATA ""
                  drawing CDATA ""
                  type CDATA ""
                  description CDATA ""
                  udf CDATA "">
   <!ELEMENT enum_definitions ANY>
   <!ATTLIST enum_definitions id ID #REQUIRED
                  name CDATA ""
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT enum_definition ANY>
   <!ATTLIST enum_definition id ID #REQUIRED
                  typeid CDATA "_0x0"
                  name CDATA ""
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT enum_value ANY>
   <!ATTLIST enum_value id ID #REQUIRED
                  typeid CDATA "_0x0"
                  name CDATA ""
                  note CDATA ""
                  index CDATA "0"
                  udf CDATA "">
   <!ELEMENT groups ANY>
   <!ATTLIST groups id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT group ANY>
   <!ATTLIST group id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT product_dataline ANY>
   <!ATTLIST product_dataline id ID #REQUIRED
                  product_identifier CDATA #REQUIRED
                  name CDATA ""
                  locked (yes | no) "no"
                  enduser_report (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  helpfile CDATA ""
                  position CDATA ""
                  cabletype CDATA ""
                  cablenumber CDATA ""
                  documentation_tag CDATA ""
                  power_group CDATA ""
                  udf CDATA "">
   <!ELEMENT dataline_input ANY>
   <!ATTLIST dataline_input id ID #REQUIRED
                  name CDATA ""
                  note CDATA ""
                  inivalue (on | off) "off"
                  address_dataline CDATA "_0x0"
                  cable_colour CDATA ""
                  udf CDATA "">
   <!ELEMENT link_from_resource ANY>
   <!ATTLIST link_from_resource id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  link IDREF #REQUIRED
                  udf CDATA "">
   <!ELEMENT dataline_output ANY>
   <!ATTLIST dataline_output id ID #REQUIRED
                  name CDATA ""
                  note CDATA ""
                  inivalue (on | off) "off"
                  backup (yes | no) "no"
                  type (led | unspecified) "unspecified"
                  address_dataline CDATA "_0x0"
                  cable_colour CDATA ""
                  udf CDATA "">
   <!ELEMENT link_to_resource ANY>
   <!ATTLIST link_to_resource id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  link IDREF #REQUIRED
                  udf CDATA "">
   <!ELEMENT scenes ANY>
   <!ATTLIST scenes id ID #REQUIRED
                  name CDATA ""
                  scene_resource IDREF #REQUIRED
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT functionblock ANY>
   <!ATTLIST functionblock id ID #REQUIRED
                  name CDATA ""
                  master_schneider_electric (yes | no) "no"
                  master_type CDATA ""
                  master_version CDATA ""
                  master_name CDATA ""
                  master_programmer CDATA ""
                  master_date_year CDATA "0"
                  master_date_month CDATA "0"
                  master_date_day CDATA "0"
                  locked (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  helpfile CDATA ""
                  udf CDATA "">
   <!ELEMENT inputs ANY>
   <!ATTLIST inputs id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_input ANY>
   <!ATTLIST resource_input id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (on | off) "off"
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT outputs ANY>
   <!ATTLIST outputs id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_output ANY>
   <!ATTLIST resource_output id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (on | off) "off"
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT settings ANY>
   <!ATTLIST settings id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_timer ANY>
   <!ATTLIST resource_timer id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  hour CDATA #REQUIRED
                  minute CDATA #REQUIRED
                  second CDATA #REQUIRED
                  millisecond CDATA #REQUIRED
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT internalsettings ANY>
   <!ATTLIST internalsettings id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT programs ANY>
   <!ATTLIST programs id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT program_simple ANY>
   <!ATTLIST program_simple id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT events ANY>
   <!ATTLIST events id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT event ANY>
   <!ATTLIST event id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  link1 IDREF #IMPLIED
                  link2 IDREF #IMPLIED
                  method CDATA "_0x0"
                  udf CDATA "">
   <!ELEMENT actions ANY>
   <!ATTLIST actions id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  type CDATA "_0x0"
                  udf CDATA "">
   <!ELEMENT action ANY>
   <!ATTLIST action id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  link1 IDREF #IMPLIED
                  link2 IDREF #IMPLIED
                  method CDATA "_0x0"
                  udf CDATA "">
   <!ELEMENT resource_scene ANY>
   <!ATTLIST resource_scene id ID #REQUIRED
                  name CDATA ""
                  note CDATA ""
                  icon CDATA "_0x89"
                  hide_dialog (yes | no) "no"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_timertime ANY>
   <!ATTLIST resource_timertime id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  hour CDATA #REQUIRED
                  minute CDATA #REQUIRED
                  second CDATA #REQUIRED
                  millisecond CDATA #REQUIRED
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_flag ANY>
   <!ATTLIST resource_flag id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (on | off) "off"
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT program_sub ANY>
   <!ATTLIST program_sub id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT conditions ANY>
   <!ATTLIST conditions id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  type (and | or) "and"
                  udf CDATA "">
   <!ELEMENT condition ANY>
   <!ATTLIST condition id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  link1 IDREF #IMPLIED
                  link2 IDREF #IMPLIED
                  method CDATA "_0x0"
                  udf CDATA "">
   <!ELEMENT resource_time ANY>
   <!ATTLIST resource_time id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  hour CDATA #REQUIRED
                  minute CDATA #REQUIRED
                  second CDATA #REQUIRED
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT event_power ANY>
   <!ATTLIST event_power id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  type (up | down) "up"
                  udf CDATA "">
   <!ELEMENT resource_enum ANY>
   <!ATTLIST resource_enum id ID #REQUIRED
                  name CDATA ""
                  typedef IDREF #REQUIRED
                  inivalue IDREF #REQUIRED
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_date ANY>
   <!ATTLIST resource_date id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  year CDATA #REQUIRED
                  month CDATA #REQUIRED
                  day CDATA #REQUIRED
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_weekday ANY>
   <!ATTLIST resource_weekday id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (monday | tuesday | wednesday | thursday | friday | saturday | sunday) "monday"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_integer ANY>
   <!ATTLIST resource_integer id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  note CDATA ""
                  inivalue CDATA "0"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT resource_counter ANY>
   <!ATTLIST resource_counter id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  note CDATA ""
                  inivalue CDATA "0"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT product_rs485_modem ANY>
   <!ATTLIST product_rs485_modem id ID #REQUIRED
                  product_identifier CDATA #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  helpfile CDATA ""
                  documentation_tag CDATA ""
                  note CDATA ""
                  position CDATA ""
                  cablecolour_0V CDATA ""
                  cablecolour_24V CDATA ""
                  cablecolour_RS485Minus CDATA ""
                  cablecolour_RS485Plus CDATA ""
                  udf CDATA "">
   <!ELEMENT group_simple ANY>
   <!ATTLIST group_simple id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_input ANY>
   <!ATTLIST modem_input id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  address CDATA #REQUIRED
                  inivalue (on | off) "off"
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_output ANY>
   <!ATTLIST modem_output id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  address CDATA #REQUIRED
                  inivalue (on | off) "off"
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_alarm_output ANY>
   <!ATTLIST modem_alarm_output id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  address CDATA #REQUIRED
                  inivalue (on | off) "off"
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_alarm_status ANY>
   <!ATTLIST modem_alarm_status id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (on | off) "off"
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_alarm_cancel ANY>
   <!ATTLIST modem_alarm_cancel id ID #REQUIRED
                  name CDATA ""
                  backup (yes | no) "no"
                  icon CDATA "_0x0"
                  note CDATA ""
                  inivalue (on | off) "off"
                  accessibility (read | write | read-write) "read-write"
                  note-2 CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_settings ANY>
   <!ATTLIST modem_settings id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_phonenumber ANY>
   <!ATTLIST modem_phonenumber id ID #REQUIRED
                  address CDATA #REQUIRED
                  phonenumber CDATA ""
                  udf CDATA "">
   <!ELEMENT modem_accesscode ANY>
   <!ATTLIST modem_accesscode id ID #REQUIRED
                  value CDATA "0"
                  minimum CDATA "0"
                  maximum CDATA "99999999"
                  udf CDATA "">
   <!ELEMENT modem_idcode ANY>
   <!ATTLIST modem_idcode id ID #REQUIRED
                  value CDATA "0"
                  minimum CDATA "0"
                  maximum CDATA "99999999"
                  udf CDATA "">
   <!ELEMENT modem_dialpause ANY>
   <!ATTLIST modem_dialpause id ID #REQUIRED
                  value CDATA "0"
                  minimum CDATA "0"
                  maximum CDATA "99999999"
                  udf CDATA "">
   <!ELEMENT modem_dialdelay ANY>
   <!ATTLIST modem_dialdelay id ID #REQUIRED
                  value CDATA "0"
                  minimum CDATA "0"
                  maximum CDATA "99999999"
                  udf CDATA "">
   <!ELEMENT modem_numberofrings ANY>
   <!ATTLIST modem_numberofrings id ID #REQUIRED
                  value CDATA "0"
                  minimum CDATA "0"
                  maximum CDATA "99999999"
                  udf CDATA "">
   <!ELEMENT documentation_modules ANY>
   <!ATTLIST documentation_modules id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT dataline_input_modules ANY>
   <!ATTLIST dataline_input_modules id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT dataline_input_module ANY>
   <!ATTLIST dataline_input_module id ID #REQUIRED
                  module_type CDATA ""
                  location CDATA ""
                  note CDATA ""
                  dataline CDATA "0"
                  udf CDATA "">
   <!ELEMENT dataline_output_modules ANY>
   <!ATTLIST dataline_output_modules id ID #REQUIRED
                  name CDATA ""
                  icon CDATA "_0x0"
                  note CDATA ""
                  udf CDATA "">
   <!ELEMENT dataline_output_module ANY>
   <!ATTLIST dataline_output_module id ID #REQUIRED
                  module_type CDATA ""
                  location CDATA ""
                  note CDATA ""
                  dataline CDATA "0"
                  udf CDATA "">
]>
<utcs_project version_major="4" version_minor="0" id1="_0x7153327" id2="_0xe0e032c" last_unique_id="_0x26ff">
   <modified year="2016" month="3" day="14" hour="14" minute="3"/>
   <customer_info name="Magnus Robertsson" address="Lillagärde 9" city="Furulund" zipcode="244 66" country="Sverige" phone="046730010" mobilephone="0702636444" email="magnus.robertsson@telia.com"/>
   <installer_info name="Magnus Robertsson"/>
   <project_info programmer="Magnus Robertsson" number="42" drawing="Elden 6" type="Villa" description="Omprogrammering från gammal IHC Controller. Initialt gjord av Magnus Gullberg."/>
   <enum_definitions id="_0x3046" name="Enumeratordefinitioner">
      <enum_definition id="_0x38147" name="Larm aktiverat">
         <enum_value id="_0x38248" name="PIR 1" index="5"/>
         <enum_value id="_0x38348" name="PIR 2" index="7"/>
         <enum_value id="_0x38448" name="PIR 3" index="8"/>
         <enum_value id="_0x38548" name="PIR 4" index="9"/>
         <enum_value id="_0x38648" name="PIR 5" index="10"/>
         <enum_value id="_0x38748" name="PIR 6" index="11"/>
         <enum_value id="_0x38848" name="PIR 7" index="12"/>
         <enum_value id="_0x38948" name="PIR 8" index="13"/>
         <enum_value id="_0x38a48" name="PIR 9" index="14"/>
         <enum_value id="_0x38b48" name="PIR 10" index="6"/>
         <enum_value id="_0x38c48" name="Sabotagekrets" index="26"/>
         <enum_value id="_0x38d48" name="Magnetkontakt" index="4"/>
         <enum_value id="_0x38e48" name="Förbikopplarzon"/>
         <enum_value id="_0x38f48" name="Överfallsknapp" index="30"/>
         <enum_value id="_0x39048" name="Ingen logg" index="3"/>
         <enum_value id="_0x39148" name="Sabotageknappsats för kodinmatning" index="25"/>
         <enum_value id="_0x39248" name="Rökdetektor 1" index="15"/>
         <enum_value id="_0x39348" name="Rökdetektor 2" index="17"/>
         <enum_value id="_0x39448" name="Rökdetektor 3" index="18"/>
         <enum_value id="_0x39548" name="Rökdetektor 4" index="19"/>
         <enum_value id="_0x39648" name="Rökdetektor 5" index="20"/>
         <enum_value id="_0x39748" name="Rökdetektor 6" index="21"/>
         <enum_value id="_0x39848" name="Rökdetektor 7" index="22"/>
         <enum_value id="_0x39948" name="Rökdetektor 8" index="23"/>
         <enum_value id="_0x39a48" name="Rökdetektor 9" index="24"/>
         <enum_value id="_0x39b48" name="Rökdetektor 10" index="16"/>
         <enum_value id="_0x39c48" name="Gassensor 1" index="1"/>
         <enum_value id="_0x39d48" name="Gassensor 2" index="2"/>
         <enum_value id="_0x39e48" name="Vattensensor 1" index="27"/>
         <enum_value id="_0x39f48" name="Vattensensor 2" index="28"/>
         <enum_value id="_0x3a048" name="Vattensensor 3" index="29"/>
      </enum_definition>
      <enum_definition id="_0x16a247" name="Släck">
         <enum_value id="_0x16a348" name="manuellt"/>
         <enum_value id="_0x16a448" name="manuellt eller automatiskt när skymningen går FRÅN" index="1"/>
      </enum_definition>
      <enum_definition id="_0x1ceb47" name="Tidur 1-7">
         <enum_value id="_0x1cec48" name="Tidur 1" index="1"/>
         <enum_value id="_0x1ced48" name="Tidur 2" index="2"/>
         <enum_value id="_0x1cee48" name="Tidur 3" index="3"/>
         <enum_value id="_0x1cef48" name="Tidur 4" index="4"/>
         <enum_value id="_0x1cf048" name="Tidur 5" index="5"/>
         <enum_value id="_0x1cf148" name="Tidur 6" index="6"/>
         <enum_value id="_0x1cf248" name="Tidur 7" index="8"/>
         <enum_value id="_0x1cf348" name="Ingen Tidursfunktion"/>
         <enum_value id="_0x1cf448" name="Tidur 6 och 7" index="7"/>
      </enum_definition>
      <enum_definition id="_0x26ee47" typeid="_0x10" name="Persienn tillstånd">
         <enum_value id="_0x26ef48" typeid="_0x11" name="Obestämd"/>
         <enum_value id="_0x26f048" typeid="_0x12" name="Uppe" index="1"/>
         <enum_value id="_0x26f148" typeid="_0x13" name="Nere" index="2"/>
         <enum_value id="_0x26f248" typeid="_0x14" name="Uppåtgående" index="3"/>
         <enum_value id="_0x26f348" typeid="_0x15" name="Nedåtgående" index="4"/>
      </enum_definition>
   </enum_definitions>
   <groups id="_0x2031" name="Lokaler/rum" icon="_0x15" note="Gruppering av produkter och funktionsblock">
      <group id="_0x2132" name="Vardagsrum" icon="_0x15">
         <product_dataline id="_0xa953" product_identifier="_0x4008" name="Tryckknapp 8-pol med 4 LED" locked="yes" enduser_report="yes" icon="_0x85" note="Tryckknapp 8-pol med 4 LED" position="Vid hall">
            <dataline_input id="_0xaa5a" name="PB (höger övre)" note="Dimma ner/släck tak" address_dataline="_0x2f" cable_colour="Grön-Vit">
               <link_from_resource id="_0xfe82d" name="Följ länk" icon="_0x47" link="_0xfe92c"/>
            </dataline_input>
            <dataline_input id="_0xab5a" name="PB (vänster övre)" note="Dimma upp/tänd tak" address_dataline="_0x30" cable_colour="Vit-Grön">
               <link_from_resource id="_0xfea2d" name="Följ länk" icon="_0x47" link="_0xfeb2c"/>
            </dataline_input>
            <dataline_input id="_0xac5a" name="PB (höger övre mitten)" note="Tänd/släck uttag" address_dataline="_0x31" cable_colour="Brun-Vit">
               <link_from_resource id="_0x10f22d" name="Följ länk" icon="_0x47" link="_0x10f32c"/>
            </dataline_input>
            <dataline_input id="_0xad5a" name="PB (vänster övre mitten)" note="Tänd/släck fönster" address_dataline="_0x32" cable_colour="Vit-Brun">
               <link_from_resource id="_0x116f2d" name="Följ länk" icon="_0x47" link="_0x11702c"/>
            </dataline_input>
            <dataline_input id="_0xae5a" name="PB (höger nedre mitten)" note="Släck ytterbelysning" address_dataline="_0x33" cable_colour="Orange-Vit">
               <link_from_resource id="_0x106d2d" name="Följ länk" icon="_0x47" link="_0x106e2c"/>
            </dataline_input>
            <dataline_input id="_0xaf5a" name="PB (vänster nedre mitten)" note="Tänd ytterbelysning" address_dataline="_0x34" cable_colour="Vit-Orange">
               <link_from_resource id="_0x106f2d" name="Följ länk" icon="_0x47" link="_0x10702c"/>
            </dataline_input>
            <dataline_input id="_0xb05a" name="PB (höger nedre)" note="Reserv" address_dataline="_0x35" cable_colour="Grå-Vit"/>
            <dataline_input id="_0xb15a" name="PB (vänster nedre)" note="Reserv" address_dataline="_0x36" cable_colour="Vit-Grå"/>
            <dataline_output id="_0xb25b" name="LED (övre)" backup="yes" type="led"/>
            <dataline_output id="_0xb35b" name="LED (övre mitten)" backup="yes" type="led"/>
            <dataline_output id="_0xb45b" name="LED (nedre mitten)" backup="yes" type="led"/>
            <dataline_output id="_0xb55b" name="LED (nedre)" backup="yes" type="led"/>
         </product_dataline>
         <product_dataline id="_0xbc53" product_identifier="_0x4008" name="Tryckknapp 8-pol med 4 LED" locked="yes" enduser_report="yes" icon="_0x85" note="Tryckknapp 8-pol med 4 LED" position="Vid altandörr">
            <dataline_input id="_0xbd5a" name="PB (höger övre)" note="Dimma ner/släck tak" address_dataline="_0x37" cable_colour="Grön-Vit">
               <link_from_resource id="_0xfec2d" name="Följ länk" icon="_0x47" link="_0xfed2c"/>
            </dataline_input>
            <dataline_input id="_0xbe5a" name="PB (vänster övre)" note="Dimma upp/tänd tak" address_dataline="_0x38" cable_colour="Vit-Grön">
               <link_from_resource id="_0xfee2d" name="Följ länk" icon="_0x47" link="_0xfef2c"/>
            </dataline_input>
            <dataline_input id="_0xbf5a" name="PB (höger övre mitten)" note="Släck ytterbelysning" address_dataline="_0x39" cable_colour="Brun-Vit">
               <link_from_resource id="_0x10712d" name="Följ länk" icon="_0x47" link="_0x10722c"/>
            </dataline_input>
            <dataline_input id="_0xc05a" name="PB (vänster övre mitten)" note="Tänd ytterbelysning" address_dataline="_0x3a" cable_colour="Vit-Brun">
               <link_from_resource id="_0x10732d" name="Följ länk" icon="_0x47" link="_0x10742c"/>
            </dataline_input>
            <dataline_input id="_0xc15a" name="PB (höger nedre mitten)" note="Släck uttag" address_dataline="_0x3b" cable_colour="Orange-Vit">
               <link_from_resource id="_0x11712d" name="Följ länk" icon="_0x47" link="_0x11722c"/>
            </dataline_input>
            <dataline_input id="_0xc25a" name="PB (vänster nedre mitten)" note="Tänd uttag" address_dataline="_0x3c" cable_colour="Vit-Orange">
               <link_from_resource id="_0x11732d" name="Följ länk" icon="_0x47" link="_0x11742c"/>
            </dataline_input>
            <dataline_input id="_0xc35a" name="PB (höger nedre)" note="Reserv" address_dataline="_0x3d" cable_colour="Grå-Vit"/>
            <dataline_input id="_0xc45a" name="PB (vänster nedre)" note="Reserv" address_dataline="_0x3e" cable_colour="Vit-Grå"/>
            <dataline_output id="_0xc55b" name="LED (övre)" backup="yes" type="led"/>
            <dataline_output id="_0xc65b" name="LED (övre mitten)" backup="yes" type="led"/>
            <dataline_output id="_0xc75b" name="LED (nedre mitten)" backup="yes" type="led"/>
            <dataline_output id="_0xc85b" name="LED (nedre)" backup="yes" type="led"/>
         </product_dataline>
         <product_dataline id="_0x12a53" product_identifier="_0x210f" name="PIR Larm" locked="yes" icon="_0x83" note="PIR med en ingång">
            <dataline_input id="_0x12b5a" name="Larmdetektering" address_dataline="_0x6c">
               <link_from_resource id="_0xb182d" name="Följ länk" icon="_0x47" link="_0xb192c"/>
            </dataline_input>
         </product_dataline>
         <product_dataline id="_0x16a53" product_identifier="_0x2202" name="Belysning" locked="yes" icon="_0x86" note="Spot i fönster" position="I fönster">
            <dataline_output id="_0x16b5b" name="Utgång" backup="yes" address_dataline="_0x19" cable_colour="Svart">
               <link_to_resource id="_0x116e2c" name="Följ länk" icon="_0x4a" link="_0x116d2d"/>
               <link_to_resource id="_0x1b6d2c" name="Följ länk" icon="_0x4a" link="_0x1b6c2d"/>
               <link_to_resource id="_0x24d72c" name="Följ länk" icon="_0x4a" link="_0x24d62d"/>
               <link_to_resource id="_0x26062c" name="Följ länk" icon="_0x4a" link="_0x26052d"/>
            </dataline_output>
            <scenes id="_0x16c49" name="Scenario" scene_resource="_0x16b5b"/>
         </product_dataline>
         <product_dataline id="_0x16d53" product_identifier="_0x2201" name="Uttag/anslutning" locked="yes" icon="_0x88">
            <dataline_output id="_0x16e5b" name="Utgång" note="Uttag vardagsrum" backup="yes" address_dataline="_0x1a" cable_colour="Grå">
               <link_to_resource id="_0x10f12c" name="Följ länk" icon="_0x4a" link="_0x10f02d"/>